// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ruyjbV6IRvqt2aknMFYhe8HbCPS7vo0',
    appId: '1:494110855091:web:2620b4fa96f7cbb11c85c6',
    messagingSenderId: '494110855091',
    projectId: 'jhkim-2bdca',
    authDomain: 'jhkim-2bdca.firebaseapp.com',
    databaseURL: 'https://jhkim-2bdca.firebaseio.com',
    storageBucket: 'jhkim-2bdca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvAxwyhar1b-aNrVDkGfn4BlHlpp0lclI',
    appId: '1:494110855091:android:dfe4983cf86b7b6d1c85c6',
    messagingSenderId: '494110855091',
    projectId: 'jhkim-2bdca',
    databaseURL: 'https://jhkim-2bdca.firebaseio.com',
    storageBucket: 'jhkim-2bdca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApfGJMQ-ynadgvyT3xt5ot39ofPTxNPQ8',
    appId: '1:494110855091:ios:1686cfed8c743fe91c85c6',
    messagingSenderId: '494110855091',
    projectId: 'jhkim-2bdca',
    databaseURL: 'https://jhkim-2bdca.firebaseio.com',
    storageBucket: 'jhkim-2bdca.firebasestorage.app',
    iosClientId: '494110855091-8ae0p8nhms047qh8jf5dkjgtr9u8t26h.apps.googleusercontent.com',
    iosBundleId: 'com.siljeok.cardSiljeok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApfGJMQ-ynadgvyT3xt5ot39ofPTxNPQ8',
    appId: '1:494110855091:ios:1686cfed8c743fe91c85c6',
    messagingSenderId: '494110855091',
    projectId: 'jhkim-2bdca',
    databaseURL: 'https://jhkim-2bdca.firebaseio.com',
    storageBucket: 'jhkim-2bdca.firebasestorage.app',
    iosClientId: '494110855091-8ae0p8nhms047qh8jf5dkjgtr9u8t26h.apps.googleusercontent.com',
    iosBundleId: 'com.siljeok.cardSiljeok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3ruyjbV6IRvqt2aknMFYhe8HbCPS7vo0',
    appId: '1:494110855091:web:39c6561f056b25df1c85c6',
    messagingSenderId: '494110855091',
    projectId: 'jhkim-2bdca',
    authDomain: 'jhkim-2bdca.firebaseapp.com',
    databaseURL: 'https://jhkim-2bdca.firebaseio.com',
    storageBucket: 'jhkim-2bdca.firebasestorage.app',
  );
}
